Repository pivotal-cf/docs-pcf-security, pull requests merged in 2018-02, with the labels that each got.

#7 Edit container credentials documentation
  networking/tls-info.html.md.erb
Labels: scheduled

#8 Update and reorganize instance-cred documentation
  networking/tls-info.html.md.erb
Labels: in progress

#9 add jmx-bridge information
  networking/jmxbridge-network-paths.html.md.erb
Labels: unscheduled
