Repository pivotal-cf/docs-pcf-security, pull requests merged in 2020-03, with the labels that each got.

#75 Update docs to match new behavior in 2.9
  pcf-infrastructure/api-cert-rotation.html.md.erb
Labels: scheduled

#76 Document the CAs that are excluded from certificate rotation
  pcf-infrastructure/api-cert-rotation.html.md.erb
Labels: in progress

#77 Include step to check Recreate all VMs before Apply Changes
  pcf-infrastructure/api-cert-rotation.html.md.erb
Labels: unscheduled

#80 2.7
  pcf-infrastructure/api-cert-rotation.html.md.erb
Labels: unscheduled

#79 2.6
  pcf-infrastructure/api-cert-rotation.html.md.erb
Labels: unscheduled

#78 Include step to check Recreate all VMs before Apply Changes
  pcf-infrastructure/api-cert-rotation.html.md.erb
Labels: unscheduled

#81 Rename column to Minimum Supported Version
  pcf-infrastructure/maestro-tile-compatibility.html.md.erb
Labels: unscheduled

#82 Rename column to Minimum Supported Version
  pcf-infrastructure/maestro-tile-compatibility.html.md.erb
Labels: unscheduled

#83 Making Step 3 as NOT Optional: Rotate Configurable Leaf Certificates
  pcf-infrastructure/api-cert-rotation.html.md.erb
Labels: unscheduled
