Repository pivotal-cf/docs-pcf-security, pull requests merged in 2020-05, with the labels that each got.

#84 add redis version to maestro tile compatibility
  pcf-infrastructure/maestro-tile-compatibility.html.md.erb
Labels: scheduled

#87 add redis version to maestro tile compatibility
  pcf-infrastructure/maestro-tile-compatibility.html.md.erb
Labels: scheduled

#86 add redis version to maestro tile compatibility
  pcf-infrastructure/maestro-tile-compatibility.html.md.erb
Labels: scheduled

#88 Add CA Rotation warning - use tile-specific procedure for GemFire
  pcf-infrastructure/api-cert-rotation.html.md.erb
Labels: unscheduled

#89 Strengthen tls_ca warning, replace KB link with Tanzu GemFire link.
  pcf-infrastructure/api-cert-rotation.html.md.erb
Labels: unscheduled

#94 Direct readers to tile-specific docs for service cert rotation
  pcf-infrastructure/api-cert-rotation.html.md.erb
Labels: unscheduled

#93 Direct readers to tile-specific docs for service cert rotation
  pcf-infrastructure/api-cert-rotation.html.md.erb
Labels: unscheduled

#92 Direct readers to tile-specific docs for service cert rotation
  pcf-infrastructure/api-cert-rotation.html.md.erb
Labels: unscheduled

#91 Direct readers to tile-specific docs for service cert rotation
  pcf-infrastructure/api-cert-rotation.html.md.erb
Labels: unscheduled

#95 Replace Tanzu GemFire link with a generic textual reference.
  pcf-infrastructure/api-cert-rotation.html.md.erb
Labels: unscheduled

#96 Warning when certificates have already expired
  pcf-infrastructure/api-cert-rotation.html.md.erb
Labels: in progress

#97 Warning when certificates have already expired
  pcf-infrastructure/api-cert-rotation.html.md.erb
Labels: in progress

#98 Warning when certificates have already expired
  pcf-infrastructure/api-cert-rotation.html.md.erb
Labels: in progress

#99 Warning when certificates have already expired
  pcf-infrastructure/api-cert-rotation.html.md.erb
Labels: in progress

#102 Relocate /services/tls_ca warning
  pcf-infrastructure/api-cert-rotation.html.md.erb
Labels: unscheduled

#101 Relocate /services/tls_ca warning
  pcf-infrastructure/api-cert-rotation.html.md.erb
Labels: unscheduled

#100 Relocate /services/tls_ca warning
  pcf-infrastructure/api-cert-rotation.html.md.erb
Labels: unscheduled
